---
# Version should be "6" or higher
elastic_branch: 6
es_version: '{{ es_major_version }}'
kibana_version: '{{ es_version }}'
kibana_port: 5601
kibana_host: localhost
kibana_user: kibana
kibana_group: kibana

kibana_home: '{{ default["kibana_home"] }}'
kibana_pid_dir: '{{ default["kibana_pid_dir"] }}'
kibana_log_dir: '{{ default["kibana_log_dir"] }}'
kibana_conf_dir: '{{ default["kibana_conf_dir"] }}'
kibana_data_dir: '{{ default["kibana_data_dir"] }}'
kibana_config: ""
elasticsearch_host: localhost
elasticsearch_port: 9200
elasticsearch_schema: https
elasticsearch_username: ""
elasticsearch_password: ""
kibana_elasticsearch_url: '{{ elasticsearch_schema }}://{{ elasticsearch_host }}:{{ elasticsearch_port }}'
elastic_gpg_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
es_apt_url: 'deb https://artifacts.elastic.co/packages/{{ es_repo_name }}/apt stable main'
es_yum_url: 'https://artifacts.elastic.co/packages/{{ es_repo_name }}/yum'
es_repo_file: 'elastic-{{ es_major_version }}'
es_use_oss_version: False
