---
- block:
    - name: Create Directories
      file:
        path: "{{ lookup('vars', kibana_path_item) }}"
        state: directory
        owner: '{{ kibana_user }}'
        group: '{{ kibana_group }}'
        recurse: false
      loop:
        - kibana_pid_dir
        - kibana_log_dir
        - kibana_conf_dir
        - kibana_data_dir
      loop_control:
        loop_var: kibana_path_item

    - name: Copy kibana configuration file
      template:
        src: kibana.yml.j2
        dest: '{{ kibana_conf_dir }}/kibana.yml'
        owner: '{{ kibana_user }}'
        group: '{{ kibana_group }}'
        mode: 0644
        force: true
      notify: Restart kibana

    - name: Copy Default File for Instance
      template:
        src: default/kibana.j2
        dest: '{{ kibana_default_file }}'
        mode: 0644
        force: true
      notify: Restart kibana

    - name: Copy service configuration file
      template:
        src: '{{ kibana_service_script }}.j2'
        dest: '{{ kibana_service_path }}/{{ kibana_service_script }}'
        mode: '{{ kibana_service_script_mode }}'
        force: true
      notify: '{{ kibana_service_handlers }}'
  become: true
