---
- name: Set kibana version if defined
  set_fact:
    kibana_package_name: '{{ kibana_package_name }}-{{ kibana_version }}'
  when: kibana_version.find('.x') == -1

- block:
    - name: Importing latest Elastic GPG Key
      rpm_key:
        key: '{{ elastic_gpg_key }}'
        state: present
      register: installed_key
      until: installed_key is succeeded

    - name: Add elasticsearch yum repository
      yum_repository:
        name: elasticsearch
        description: Elasticsearch repository
        file: '{{ es_repo_file }}'
        baseurl: '{{ es_yum_url }}'
        gpgcheck: true
        gpgkey: '{{ elastic_gpg_key }}'
        enabled: true
        state: present

    - name: Install pip
      yum:
        name: python-pip
        update_cache: yes
        state: present

    - name: Redhat - Installing Kibana package
      yum:
        name: '{{ kibana_package_name }}'
        state: present
        update_cache: true
      register: installed_package
      until: installed_package is succeeded
      notify: Restart kibana
  become: true
